#
# Copyright (c) 2023-2024 Fraunhofer-Gesellschaft zur FÃ¶rderung der angewandten Forschung e.V.
#
# This work is licensed under the Fraunhofer License (on the basis of the MIT license)
# that can be found in the LICENSE file.
#

name: "Test: Webinterface"

on:
  push:
    branches: [ main ]
    paths: [ "webinterface/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "webinterface/**" ]
  release:
    types: [ published ]

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint-code:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Lint Code
        id: lint
        working-directory: webinterface
        run: ./gradlew ktlintCheck

  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Publish watermarker to mavenLocal
        working-directory: watermarker
        run: ./gradlew publishToMavenLocal

      - name: Run tests
        id: test
        working-directory: webinterface
        run: ./gradlew test

  verify-docker:
    name: Verify Dockerfile Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker Image
        run: docker build -t trend-webinterface -f webinterface/Dockerfile .
